import { useEffect, useMemo, useState } from 'react'
import { evaluateDistance, histogram, reproject, saveAnnotations, stats, systemInfo } from '../api/client'
import { useSceneStore } from '../store/useSceneStore'

export function AnalysisPanel(){
 const s=useSceneStore(),scene=s.scene,profile=s.profile,region=s.regionResult
 const [h,setH]=useState<any>(null),[st,setSt]=useState<any>(null),[sys,setSys]=useState<any>(null),[known,setKnown]=useState(''),[evalResult,setEvalResult]=useState<any>(null),[reproj,setReproj]=useState<any>(null)
 useEffect(()=>{if(scene){Promise.all([histogram(scene.scene_id),stats(scene.scene_id),systemInfo()]).then(([hh,ss,sys0])=>{setH(hh);setSt(ss);setSys(sys0)}).catch(()=>{})}},[scene?.scene_id])
 useEffect(()=>{if(scene&&s.selected)reproject(scene.scene_id,[s.selected.x_m,s.selected.y_m,s.selected.z_m]).then(setReproj).catch(()=>setReproj(null))},[scene?.scene_id,s.selected])
 const max=Math.max(...(h?.counts||[1]));
 const evalNow=async()=>{if(!scene||!s.measurementA||!s.measurementB||!known)return;const pred=Math.hypot(s.measurementB.x_m-s.measurementA.x_m,s.measurementB.y_m-s.measurementA.y_m,s.measurementB.z_m-s.measurementA.z_m);try{setEvalResult(await evaluateDistance(scene.scene_id,pred,+known))}catch{setEvalResult(null)}}
 const depthRange=useMemo(()=>st?`${st.min_m.toFixed(2)}–${st.max_m.toFixed(2)} m`:'—',[st])
 if(!scene)return null
 return <div className="analysisPanel panelScroll">
  <section><h3>DEPTH STATISTICS</h3>{st&&<div className="statGrid"><Stat n="Median" v={`${st.median_m.toFixed(2)} m`}/><Stat n="Mean" v={`${st.mean_m.toFixed(2)} m`}/><Stat n="Std dev" v={`${st.std_m.toFixed(2)} m`}/><Stat n="Valid" v={`${(st.valid_fraction*100).toFixed(1)}%`}/><Stat n="Range" v={depthRange}/><Stat n="P95" v={`${st.percentiles_m?.p95?.toFixed(2)??'—'} m`}/></div>}{h&&<><div className="histogram">{h.counts.map((v:number,i:number)=><i key={i} role="button" onClick={()=>s.set({nearDepth:Math.max(.05,h.edges_m[i]||.05),farDepth:Math.max((h.edges_m[i+1]||scene.depth_max_m), (h.edges_m[i]||.05)+.01)})} style={{height:`${Math.max(2,v/max*100)}%`}} title={`Click to clip ${h.edges_m[i]?.toFixed(2)}–${h.edges_m[i+1]?.toFixed(2)} m`}/>)}</div><div className="small">{h.counts.length} bins · click a bin to focus the corresponding depth range.</div></>}</section>
  <section><h3>RECONSTRUCTION QUALITY</h3><div className="qualityBox"><div><span>Depth score</span><b>{scene.quality.depth_quality?.label??'—'}</b></div><div><span>Valid pixels</span><b>{((scene.quality.depth_valid_fraction??0)*100).toFixed(1)}%</b></div><div><span>Smoothness</span><b>{((scene.quality.depth_quality?.smoothness??0)*100).toFixed(0)}%</b></div><div><span>Calibration</span><b>{scene.calibration.quality?.label??'—'}</b></div><div><span>Planes</span><b>{scene.planes.length}</b></div><div><span>Mesh</span><b>{scene.quality.mesh_generated?'READY':'—'}</b></div></div></section>
  {region&&<section><h3>REGION / ROI</h3><div className="statGrid"><Stat n="Pixels" v={region.pixel_count.toLocaleString()}/><Stat n="Valid depth" v={region.valid_depth_pixels.toLocaleString()}/><Stat n="Median depth" v={region.depth_median_m==null?'—':`${region.depth_median_m.toFixed(2)} m`}/><Stat n="Width" v={region.dimensions_m?`${region.dimensions_m[0].toFixed(2)} m`:'—'}/><Stat n="Height" v={region.dimensions_m?`${region.dimensions_m[1].toFixed(2)} m`:'—'}/><Stat n="Area est." v={region.surface_area_m2==null?'—':`${region.surface_area_m2.toFixed(2)} m²`}/><Stat n="BBox volume" v={region.bbox_volume_m3==null?'—':`${region.bbox_volume_m3.toFixed(2)} m³`}/></div></section>}
  {profile&&<section><h3>DEPTH PROFILE</h3><Profile data={profile.depth_m}/><div className="small">{profile.start.join(', ')} → {profile.end.join(', ')} · {profile.samples} samples · 3D path ≈ {(profile.distance_m.at(-1)??0).toFixed(2)} m</div></section>}
  <section><h3>MEASUREMENT VALIDATION</h3><div className="small">With A and B selected, enter a known real distance to quantify this reconstruction's measurement error.</div><div className="rangePair"><input type="number" min=".001" step=".01" placeholder="Known distance (m)" value={known} onChange={e=>setKnown(e.target.value)}/><button disabled={!s.measurementA||!s.measurementB||!known} onClick={evalNow}>Evaluate</button></div>{evalResult&&<div className="measurementCard"><span>Predicted</span><strong>{evalResult.predicted_distance_m.toFixed(3)} m</strong><span>Error</span><strong>{evalResult.absolute_error_m.toFixed(3)} m · {evalResult.relative_error_percent.toFixed(2)}%</strong></div>}</section>
  {s.selected&&<section><h3>REPROJECTION CHECK</h3><div className="small">Projects the selected metric point back through K. This validates the camera/coordinate transform consistency.</div>{reproj&&<div className="statGrid"><Stat n="Original pixel" v={`${s.selected.pixel_x}, ${s.selected.pixel_y}`}/><Stat n="Projected" v={`${reproj.pixel_x.toFixed(2)}, ${reproj.pixel_y.toFixed(2)}`}/><Stat n="Inside image" v={reproj.inside?'YES':'NO'}/></div>}</section>}
  <section><h3>ANNOTATIONS</h3>{s.annotations.length?<div className="annotationList">{s.annotations.map(a=><div className="annotationRow" key={a.id}><button onClick={()=>s.set({selected:a.point,cameraView:'selected'})}><b>{a.name}</b><span>{a.point.x_m.toFixed(2)}, {a.point.y_m.toFixed(2)}, {a.point.z_m.toFixed(2)} m</span></button><button className="dangerMini" onClick={async()=>{const next=s.annotations.filter(x=>x.id!==a.id);s.set({annotations:next});if(scene)await saveAnnotations(scene.scene_id,next)}}>×</button></div>)}</div>:<div className="small">Use Annotate mode to pin named 3D coordinates to the image.</div>}</section>
  {s.annotations.length>=2&&<section><h3>ANNOTATION DISTANCES</h3><div className="distanceMatrix">{s.annotations.map((a,i)=><div key={a.id} className="distanceRow"><b>{a.name}</b><span>{s.annotations.filter((_,j)=>j!==i).slice(0,3).map(b=>`${b.name}: ${Math.hypot(b.point.x_m-a.point.x_m,b.point.y_m-a.point.y_m,b.point.z_m-a.point.z_m).toFixed(2)} m`).join(' · ')}</span></div>)}</div></section>}
  <section><h3>MODEL & PIPELINE</h3><div className="qualityBox"><div><span>Model</span><b>{scene.model}</b></div><div><span>Dataset</span><b>{scene.model_dataset}</b></div><div><span>Input</span><b>{scene.quality.model_input_size??'—'} px</b></div><div><span>Inference</span><b>{scene.quality.inference_seconds??'—'} s</b></div><div><span>Points</span><b>{scene.point_counts[0].toLocaleString()}</b></div><div><span>Frame</span><b>CAMERA / METERS</b></div><div><span>Source revision</span><b>{scene.model_source_commit.slice(0,8)}</b></div><div><span>Device</span><b>{sys?.gpu_name||sys?.device||'—'}</b></div><div><span>VRAM allocated</span><b>{sys?.gpu_memory?`${(sys.gpu_memory.allocated_bytes/1073741824).toFixed(2)} GB`:'—'}</b></div></div></section>
 </div>
}
const Stat=({n,v}:{n:string;v:string})=><div className="stat"><span>{n}</span><b>{v}</b></div>
function Profile({data}:{data:(number|null)[]}){const vals=data.filter((v):v is number=>v!=null),mn=vals.length?Math.min(...vals):0,mx=vals.length?Math.max(...vals):1;const points=data.map((v,i)=>v==null?null:[i/(Math.max(data.length-1,1))*100,100-(v-mn)/Math.max(mx-mn,1e-6)*92]).filter(Boolean) as [number,number][];return <div className="profileChart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points.map(([x,y])=>`${x},${y}`).join(' ')} /></svg><div className="profileAxis"><span>{mn.toFixed(2)} m</span><span>{mx.toFixed(2)} m</span></div></div>}
