import { useEffect, useState, type ReactNode } from 'react'
import { calibrateReference, getScene, segment, updateCalibration } from '../api/client'
import { useSceneStore } from '../store/useSceneStore'
import type { ColorMode, RegionShape } from '../types'

export function Controls(){
 const s=useSceneStore(), [calSource,setCalSource]=useState<'auto'|'fov'|'manual'>('auto'),[fov,setFov]=useState('70'),[fx,setFx]=useState(''),[fy,setFy]=useState(''),[cx,setCx]=useState(''),[cy,setCy]=useState(''),[k1,setK1]=useState('0'),[k2,setK2]=useState('0'),[p1,setP1]=useState('0'),[p2,setP2]=useState('0'),[k3,setK3]=useState('0'),[ref,setRef]=useState('1.00'),[segScore,setSegScore]=useState(.65),[message,setMessage]=useState('')
 useEffect(()=>{if(!s.scene)return;const c=s.scene.calibration;setCalSource(c.source==='manual'?'manual':c.source==='fov'?'fov':'auto');setFov(String(c.fov_x_deg??c.fov_deg??70));setFx(String(c.fx));setFy(String(c.fy));setCx(String(c.cx));setCy(String(c.cy));setK1(String(c.distortion?.k1??0));setK2(String(c.distortion?.k2??0));setP1(String(c.distortion?.p1??0));setP2(String(c.distortion?.p2??0));setK3(String(c.distortion?.k3??0))},[s.scene])
 const applyCal=async()=>{if(!s.sceneId)return;try{const payload={source:calSource,scale:s.scene?.calibration.scale||1,k1:+k1,k2:+k2,p1:+p1,p2:+p2,k3:+k3,...(calSource==='manual'?{fx:+fx,fy:+fy,cx:+cx,cy:+cy}:{fov_deg:+fov})};await updateCalibration(s.sceneId,payload);const scene=await getScene(s.sceneId);s.set({scene,selected:null,measurementA:null,measurementB:null,measurementC:null,profile:null,regionResult:null});setMessage('Calibration applied and geometry rebuilt.')}catch(e){setMessage(String(e))}}
 const applyRef=async()=>{if(!s.sceneId||!s.measurementA||!s.measurementB)return;try{await calibrateReference(s.sceneId,{x1:s.measurementA.pixel_x,y1:s.measurementA.pixel_y,x2:s.measurementB.pixel_x,y2:s.measurementB.pixel_y,known_distance_m:+ref});const scene=await getScene(s.sceneId);s.set({scene,selected:null});setMessage('Reference scale applied.')}catch(e){setMessage(String(e))}}
 const runSeg=async()=>{if(!s.sceneId)return;try{const out=await segment(s.sceneId,segScore,12);const scene=await getScene(s.sceneId);s.set({scene,selectedObjectId:out.objects?.[0]?.id??null});setMessage(`Detected ${out.objects?.length??0} objects with 3D statistics.`)}catch(e){setMessage(String(e))}}
 return <aside className="controls panelScroll">
  <Section title="POINT CLOUD">
   <Field label={`Density · ${['Maximum','High','Balanced','Preview'][s.density]}`}><select value={s.density} onChange={e=>s.set({density:+e.target.value as 0|1|2|3})}><option value={0}>Maximum</option><option value={1}>High</option><option value={2}>Balanced</option><option value={3}>Preview</option></select></Field>
   <Field label={`Point size · ${s.pointSize.toFixed(1)}`}><input type="range" min=".5" max="8" step=".1" value={s.pointSize} onChange={e=>s.set({pointSize:+e.target.value})}/></Field>
   <Field label={`GPU budget · ${(s.pointBudget/1e6).toFixed(1)}M`}><input type="range" min="100000" max="3000000" step="100000" value={s.pointBudget} onChange={e=>s.set({pointBudget:+e.target.value})}/></Field>
   <Field label={`Opacity · ${Math.round(s.pointOpacity*100)}%`}><input type="range" min=".2" max="1" step=".01" value={s.pointOpacity} onChange={e=>s.set({pointOpacity:+e.target.value})}/></Field>
   <Field label="Color mode"><select value={s.colorMode} onChange={e=>s.set({colorMode:e.target.value as ColorMode})}><option value="rgb">RGB</option><option value="depth">Depth</option><option value="height">Height</option><option value="normal">Normal</option><option value="object">Selected object</option></select></Field>
  </Section>
  <Section title="CLIPPING"><Field label="Depth range"><div className="rangePair"><input type="number" min=".01" step=".01" value={s.nearDepth} onChange={e=>s.set({nearDepth:+e.target.value})}/><input type="number" min=".1" step=".1" value={s.farDepth} onChange={e=>s.set({farDepth:+e.target.value})}/></div></Field><Field label="X range"><div className="rangePair"><input value={Number.isFinite(s.minX)?s.minX:''} placeholder="min" onChange={e=>s.set({minX:e.target.value===''?-Infinity:+e.target.value})}/><input value={Number.isFinite(s.maxX)?s.maxX:''} placeholder="max" onChange={e=>s.set({maxX:e.target.value===''?Infinity:+e.target.value})}/></div></Field><Field label="Y range"><div className="rangePair"><input value={Number.isFinite(s.minY)?s.minY:''} placeholder="min" onChange={e=>s.set({minY:e.target.value===''?-Infinity:+e.target.value})}/><input value={Number.isFinite(s.maxY)?s.maxY:''} placeholder="max" onChange={e=>s.set({maxY:e.target.value===''?Infinity:+e.target.value})}/></div></Field><Field label="Z range"><div className="rangePair"><input value={Number.isFinite(s.minZ)?s.minZ:''} placeholder="min" onChange={e=>s.set({minZ:e.target.value===''?-Infinity:+e.target.value})}/><input value={Number.isFinite(s.maxZ)?s.maxZ:''} placeholder="max" onChange={e=>s.set({maxZ:e.target.value===''?Infinity:+e.target.value})}/></div></Field></Section>
  <Section title="DEPTH DISPLAY"><Field label="Colormap"><select value={s.depthColormap} onChange={e=>s.set({depthColormap:e.target.value as any})}><option value="turbo">Turbo</option><option value="viridis">Viridis</option><option value="jet">Jet</option><option value="magma">Magma</option><option value="inferno">Inferno</option><option value="plasma">Plasma</option><option value="grayscale">Grayscale</option></select></Field><Field label="Display"><select value={s.depthDisplay} onChange={e=>s.set({depthDisplay:e.target.value as any})}><option value="metric">Metric depth</option><option value="inverse">Inverse depth</option><option value="log">Log depth</option></select></Field><Toggle label="Depth contours" checked={s.showContours} onChange={v=>s.set({showContours:v})}/></Section>
  <Section title="VIEW"><Toggle label="RGB colors" checked={s.rgb} onChange={v=>s.set({rgb:v})}/><Toggle label="Grid" checked={s.showGrid} onChange={v=>s.set({showGrid:v})}/><Toggle label="Axes" checked={s.showAxes} onChange={v=>s.set({showAxes:v})}/><Toggle label="Camera frustum" checked={s.showFrustum} onChange={v=>s.set({showFrustum:v})}/><Toggle label="Camera marker" checked={s.showCamera} onChange={v=>s.set({showCamera:v})}/><Toggle label="Detected planes" checked={s.showPlanes} onChange={v=>s.set({showPlanes:v})}/><Toggle label="Ground alignment" checked={s.showGround} onChange={v=>s.set({showGround:v})}/><Toggle label="Surface mesh" checked={s.showMesh} disabled={!s.scene?.artifacts.mesh_glb} onChange={v=>s.set({showMesh:v})}/><Toggle label="Adaptive LOD" checked={s.adaptiveLod} onChange={v=>s.set({adaptiveLod:v})}/><Toggle label="3D labels" checked={s.showLabels} onChange={v=>s.set({showLabels:v})}/><Field label="Background"><input className="colorInput" type="color" value={s.background} onChange={e=>s.set({background:e.target.value})}/></Field><button className="full" onClick={()=>s.requestCameraReset()}>Reset camera</button></Section>
  <Section title="CAMERA CALIBRATION"><Field label="Method"><select value={calSource} onChange={e=>setCalSource(e.target.value as any)}><option value="auto">Automatic / EXIF fallback</option><option value="fov">FOV estimate</option><option value="manual">Manual intrinsics</option></select></Field>{calSource==='fov'?<Field label="Horizontal FOV (deg)"><input type="number" min="5" max="175" step=".1" value={fov} onChange={e=>setFov(e.target.value)}/></Field>:calSource==='manual'?<><Field label="fx (px)"><input type="number" min="1" value={fx} onChange={e=>setFx(e.target.value)}/></Field><Field label="fy (px)"><input type="number" min="1" value={fy} onChange={e=>setFy(e.target.value)}/></Field><Field label="cx (px)"><input type="number" min="0" value={cx} onChange={e=>setCx(e.target.value)}/></Field><Field label="cy (px)"><input type="number" min="0" value={cy} onChange={e=>setCy(e.target.value)}/></Field></>:<div className="small">Uses EXIF 35mm metadata when available, otherwise documented FOV fallback.</div>}<details className="advancedDetails"><summary>Lens distortion (OpenCV)</summary><div className="rangePair"><input type="number" step=".0001" value={k1} onChange={e=>setK1(e.target.value)} placeholder="k1"/><input type="number" step=".0001" value={k2} onChange={e=>setK2(e.target.value)} placeholder="k2"/></div><div className="rangePair"><input type="number" step=".0001" value={p1} onChange={e=>setP1(e.target.value)} placeholder="p1"/><input type="number" step=".0001" value={p2} onChange={e=>setP2(e.target.value)} placeholder="p2"/></div><input type="number" className="full" step=".0001" value={k3} onChange={e=>setK3(e.target.value)} placeholder="k3"/></details><button className="full" onClick={applyCal}>Apply & rebuild</button></Section>
  <Section title="REFERENCE SCALE"><div className="small">Set A and Set B using Inspect/Measure. Enter the real separation to correct global metric scale.</div><Field label="Known distance (m)"><input type="number" min=".001" step=".01" value={ref} onChange={e=>setRef(e.target.value)}/></Field><button className="full" disabled={!s.measurementA||!s.measurementB} onClick={applyRef}>Calibrate scale</button></Section>
  <Section title="OBJECTS"><div className="small">On-demand COCO instance segmentation. Detected objects receive depth, 3D bounds, centroid and approximate dimensions.</div><Field label={`Minimum score · ${segScore.toFixed(2)}`}><input type="range" min=".3" max=".95" step=".01" value={segScore} onChange={e=>setSegScore(+e.target.value)}/></Field><button className="full" onClick={runSeg}>Detect objects</button>{s.scene?.segmentation.objects.length? <div className="objectList">{s.scene.segmentation.objects.map(o=><button key={o.id} className={s.selectedObjectId===o.id?'activeMini':''} onClick={()=>s.set({selectedObjectId:o.id})}>{o.label} <span>{(o.score*100).toFixed(0)}%</span></button>)}</div>:null}</Section>
  <Section title="TOOLS"><div className="toolHintGrid"><button onClick={()=>s.set({tool:'region',regionPoints:[],regionResult:null})}>Region ROI</button><button onClick={()=>s.set({tool:'profile',profileStart:null,profile:null})}>Depth profile</button><button onClick={()=>s.set({tool:'measure'})}>Measure</button><button onClick={()=>s.set({tool:'inspect'})}>Inspect</button></div><Field label="ROI interaction"><select value={s.regionShape} onChange={e=>s.set({regionShape:e.target.value as RegionShape,regionPoints:[],regionResult:null})}><option value="polygon">Polygon / lasso-click</option><option value="rectangle">Rectangle</option><option value="lasso">Freehand lasso</option></select></Field><div className="small">Polygon: click vertices + DONE/double-click. Rectangle: drag by two clicks. Freehand lasso: click-drag around the region.</div></Section><Section title="HISTORY"><div className="measureBtns"><button onClick={()=>s.snapshot()}>Snapshot</button><button disabled={!s.history.length} onClick={()=>s.undo()}>Undo</button><button disabled={!s.future.length} onClick={()=>s.redo()}>Redo</button></div></Section>
  {message&&<div className="notice">{message}</div>}
 </aside>
}
function Section({title,children}:{title:string;children:ReactNode}){return <section><h3>{title}</h3>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Toggle({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="toggle"><input type="checkbox" disabled={disabled} checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
